version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

networks:
  inception_network:
    #driver: bridge
    name: inception_network

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data
