version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    networks:
      - inception_network
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception_network
    depends_on:
      - wordpress

networks:
  inception_network:

volumes:
  mariadb_data:
  wordpress_data:
