version: '3.7' # TODO: tentar 3.8

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: "no"
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: "no"
    env_file:
      - .env

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    ports:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: "no"


networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/pedgonca/data/mysql
      o: bind
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/pedgonca/data/wordpress
      o: bind
